services:
  postgres:
    image: postgres:16
    container_name: risky_postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow:
    image: 140023298356.dkr.ecr.<REGION>.amazonaws.com/risky-mlflow:latest
    container_name: risky_mlflow
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      MLFLOW_TRACKING_URI: "${MLFLOW_TRACKING_URI}"
      MLFLOW_SERVER_ALLOWED_HOSTS: "localhost,127.0.0.1,<EC2_PUBLIC_IP>,<EC2_PUBLIC_DNS>"
      MLFLOW_SERVER_CORS_ALLOWED_ORIGINS: "http://localhost:5001"
    ports:
      - "5001:5001"
    volumes:
      - mlflow_artifacts:/mlflow/artifacts

  app-api:
    image: 140023298356.dkr.ecr.<REGION>.amazonaws.com/risky-api:latest
    container_name: risky_api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mlflow
    environment:
      PYTHONPATH: /app
      MLFLOW_TRACKING_URI: http://mlflow:5001
    ports:
      - "8002:8002"

volumes:
  postgres_data:
  mlflow_artifacts: