name: Deploy to amazon

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Continuous deployment to ECS
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ROLE_TO_ASSUME: ${{ vars.AWS_ROLE_TO_ASSUME }}
#      ECS_CLUSTER: ${{ vars.ECS_CLUSTER }}
#      ECS_SERVICE: ${{ vars.ECS_SERVICE }}
#      ECS_TASK_DEFINITION: ${{ vars.ECS_TASK_DEFINITION }}
      CONTAINER_NAME: Main

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image App-api
        id: build-image-app-api
        env:
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY_APP_API }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: is-player-risky-app-api
        run: |
          set -e
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Build Docker image Mlflow
        id: build-image-mlflow
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: is-player-risky-mlflow
          ECR_REPOSITORY_MLFLOW: ${{ vars.ECR_REPOSITORY_MLFLOW }}
        run: |
          set -e
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_MLFLOW:$IMAGE_TAG ./mlflow
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_MLFLOW:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY_MLFLOW:$IMAGE_TAG" >> $GITHUB_OUTPUT

#      - name: Render Amazon ECS task definition
#        id: task-def
#        uses: aws-actions/amazon-ecs-render-task-definition@v1
#        with:
#          task-definition: ${{ env.ECS_TASK_DEFINITION }}
#          container-name: ${{ env.CONTAINER_NAME }}
#          image: ${{ steps.build-image.outputs.image }}
#
#      - name: Deploy Amazon ECS task definition
#        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
#        with:
#          task-definition: ${{ steps.task-def.outputs.task-definition }}
#          service: ${{ env.ECS_SERVICE }}
#          cluster: ${{ env.ECS_CLUSTER }}
#          wait-for-service-stability: true